Added check for graphql extensions.cost.throttleStatus
Shopify doesn't return throttleStatus for "staff" plan which causes the error below.

TypeError: Cannot read property 'currentlyAvailable' of undefined
    at Shopify.updateGraphqlLimits (/var/app/current/node_modules/shopify-api-node/index.js:191:31)
    at /var/app/current/node_modules/shopify-api-node/index.js:234:12
    at tryCatcher (/var/app/current/node_modules/bluebird/js/release/util.js:16:23)